/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage.vistas;

import AccesoADatos.MateriaData;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import newpackage.entidades.Materia;

/**
 *
 * @author Gregorio
 */
public class FormularioMateria extends javax.swing.JInternalFrame {

    private Connection con = null;
    private boolean mdfActivado = false;
    private boolean gdActivado = false;
    private MateriaData materiaData = new MateriaData();
    private Materia materia = new Materia();

    public FormularioMateria() {
        initComponents();
        jTfNombre.setEditable(false);
        jTfNombre.setBackground(Color.gray);
        jTfAnio.setEditable(false);
        jTfAnio.setBackground(Color.gray);
        jRbEstado.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBModificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTfCodigo = new javax.swing.JTextField();
        jTfNombre = new javax.swing.JTextField();
        jTfAnio = new javax.swing.JTextField();
        jRbEstado = new javax.swing.JRadioButton();
        jBEliminar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Formulario Materia");
        setPreferredSize(new java.awt.Dimension(616, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jTfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 230, -1));
        getContentPane().add(jTfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 300, -1));
        getContentPane().add(jTfAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 300, -1));
        getContentPane().add(jRbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jBEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-basura-501.png"))); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        jBNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-más-50.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jBGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-guardar-50.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jBModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-editar-50.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jBSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-salir-50.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-26.png"))); // NOI18N
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Materias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 18, -1, 60));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 84, 415, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Estado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Codigo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 177, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("Año:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfCodigoActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        
        jTfNombre.setEditable(false);
        jTfNombre.setBackground(Color.gray);
        jTfAnio.setEditable(false);
        jTfAnio.setBackground(Color.gray);
        jRbEstado.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBModificar.setEnabled(false);
        jTfCodigo.setEditable(true);
        jTfCodigo.setBackground(Color.white);

        int codigo = 0;

        try { //Bloque TRY-CATCH para verificar si el codigo es valido.
            codigo = Integer.parseInt(jTfCodigo.getText());
            materia = materiaData.buscarMateria(Integer.parseInt(jTfCodigo.getText()));
            if (materia != null) {
                jTfNombre.setText(materia.getNombre());
                jTfAnio.setText(String.valueOf(materia.getAnioMateria()));
                jRbEstado.setSelected(materia.isActivo());
                if (!jTfNombre.getText().equals("")) {
                    jBModificar.setEnabled(true); //Actviar boton de modificar
                    jBEliminar.setEnabled(true); //Activar boton de eliminar
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
            return;
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        
        try { //Bloque TRY-CATCH para verificar si el codigo es valido.
            materia.setIdMateria(Integer.parseInt(jTfCodigo.getText()));
            materia.setNombre(jTfNombre.getText());
            materia.setAnioMateria(Integer.parseInt(jTfAnio.getText()));
            materia.setActivo(jRbEstado.isSelected());
            materiaData.eliminarMateria(materia);
            jBBuscar.doClick();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
            return;
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
                //If para activar tocando Button Modificar y al volver a tocarlo lo desactiva
        if (mdfActivado == false) {
            jTfNombre.setEditable(true); //Activa TextField Nombre
            jTfNombre.setBackground(Color.white); //Cambia de color a blanco
            jTfAnio.setEditable(true); //Activa TextField Año
            jTfAnio.setBackground(Color.white); //Cambia de color a blanco
            jRbEstado.setEnabled(true); //Activa RadioButton Estado
            jTfCodigo.setEditable(false); //Desactiva TextField Codigo
            jTfCodigo.setBackground(Color.gray); //Cambia de color a gris
            mdfActivado = true; //Pasa a true el mdfActivado
            jBEliminar.setEnabled(false); //Desactiva Button Eliminar
            jBGuardar.setEnabled(true); //Activa el Button Guardar
        } else {
            jTfNombre.setEditable(false); //Activa TextField Nombre
            jTfNombre.setBackground(Color.gray); //Cambia de color a blanco
            jTfAnio.setEditable(false); //Activa TextField Año
            jTfAnio.setBackground(Color.gray); //Cambia de color a blanco
            jRbEstado.setEnabled(false); //Activa RadioButton Estado
            jTfCodigo.setEditable(true); //Activa TextField Codigo
            jTfCodigo.setBackground(Color.white); //Cambia de color a blanco
            mdfActivado = false; //Pasa a false el mdfActivado
            jBEliminar.setEnabled(true); //Activa Button Eliminar
            jBGuardar.setEnabled(false); //Desactiva el Button Guardar
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
                int codigo = 0;

        if (mdfActivado) {
            try { //Bloque TRY-CATCH para verificar si el codigo es valido.
                codigo = Integer.parseInt(jTfCodigo.getText());
                if (jTfNombre.getText().equals("")) { //Verifica que no sea una cadena vacia
                    JOptionPane.showMessageDialog(null, "Ingrese un nombre valido"); //Dialogo de nombre invalido
                    return;
                }
                materia.setNombre(jTfNombre.getText());
                materia.setAnioMateria(Integer.parseInt(jTfAnio.getText()));
                materia.setActivo(jRbEstado.isSelected());
                materia.setIdMateria(codigo);
                materiaData.modificarMateria(materia);
                jBModificar.doClick(); //Simulacion de click en el boton modificar para desactivar botones y textfield
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
                return;
            }
        } else {
            if (jTfNombre.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese un nombre valido"); //Dialogo de nombre invalido
                return;
            }
            try{
            materia.setNombre(jTfNombre.getText());
            materia.setAnioMateria(Integer.parseInt(jTfAnio.getText()));
            materia.setActivo(jRbEstado.isSelected());
            materia.setIdMateria(-1);
            materiaData.agregarMateria(materia);
            jBNuevo.doClick();
            }catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Ingrese un numero valido");
                return;
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        
        if (gdActivado == false) {
            jTfNombre.setEditable(true); //Activar TextField Nombre
            jTfNombre.setBackground(Color.white); //Cambiar de color a white
            jTfNombre.setText(""); //Vaciar TextField
            jTfAnio.setEditable(true); //Activar TextField 
            jTfAnio.setBackground(Color.white); //Cambiar de color a white
            jTfAnio.setText(""); //Vaciar TextField
            jRbEstado.setEnabled(false); //Desactivar RadioButton Estado
            jRbEstado.setSelected(true); //Seleccionar RadioButton Estado
            jTfCodigo.setEditable(false); //Desactivar TextField Codigo
            jTfCodigo.setBackground(Color.gray); //Cambiar de color a gray
            jTfCodigo.setText(""); //Vaciar TextField
            jBModificar.setEnabled(false); //Desactivar boton Modificar
            jBEliminar.setEnabled(false); //Desactivar boton Eliminar
            jBGuardar.setEnabled(true); //Activar boton Guardar
            gdActivado = true;
        } else {
            jTfNombre.setEditable(false);
            jTfNombre.setBackground(Color.gray);
            jTfAnio.setEditable(false);
            jTfAnio.setBackground(Color.gray);
            jRbEstado.setEnabled(false);
            jBEliminar.setEnabled(false);
            jBGuardar.setEnabled(false);
            jBModificar.setEnabled(false);
            jTfCodigo.setEditable(true); //Desactivar TextField Codigo
            jTfCodigo.setBackground(Color.white); //Cambiar de color a white
            jTfCodigo.setText(""); //Vaciar TextField
            jTfAnio.setText(""); //Vaciar TextField
            jTfNombre.setText(""); //Vaciar TextField
            jRbEstado.setSelected(false); //Deseleccionar RadioButton Estado
            gdActivado = false;
        }
    }//GEN-LAST:event_jBNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRbEstado;
    private javax.swing.JRadioButton jRbEstado1;
    private javax.swing.JRadioButton jRbEstado2;
    private javax.swing.JRadioButton jRbEstado3;
    private javax.swing.JRadioButton jRbEstado4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTfAnio;
    private javax.swing.JTextField jTfCodigo;
    private javax.swing.JTextField jTfNombre;
    private javax.swing.JTextField jTfNombre1;
    private javax.swing.JTextField jTfNombre2;
    private javax.swing.JTextField jTfNombre3;
    private javax.swing.JTextField jTfNombre4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
