/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage.vistas;

import AccesoADatos.AlumnoData;
import java.sql.Date;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import newpackage.entidades.Alumno;

/**
 *
 * @author Li Donni
 */
public class FormularioAlumnos extends javax.swing.JInternalFrame {

    private boolean alumnoEncontrado = false;
    private int codigoAlumno = 0;

    public FormularioAlumnos() {
        initComponents();
        IniciarControles();// LLAMO AL METODO PARA INICIAR LOS CONTROLES
        JDateFechaNacimiento.setDateFormatString("dd/MM/yyyy"); //ASIGNO EL FORMATO DE LA FECHA

    }

    //INICIALIZO LOS CONTROLES
    private void IniciarControles() {
        //LIMPIO LOS TEXTBOX
        jTextDni.setText("");
        jTextNombre.setText("");
        jTextApellido.setText("");
        jRBEstado.setSelected(true);
        jRBEstado.setEnabled(false);
        jTextDni.setEnabled(true);
        //INICIO LOS BOTONES
        jBtnEliminar.setEnabled(false);
        jBtnGuardar.setEnabled(true);
        jBtnGuardar.setVisible(true);
        jBtnModificar.setEnabled(false);
        jBtnModificar.setVisible(false);
        alumnoEncontrado = false;
        codigoAlumno = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextNombre = new javax.swing.JTextField();
        jRBEstado = new javax.swing.JRadioButton();
        jBtnNuevo = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextDni = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        JDateFechaNacimiento = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setTitle("Alumno");
        setName(""); // NOI18N

        jBtnNuevo.setText("Nuevo");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.setMaximumSize(new java.awt.Dimension(69, 23));
        jBtnSalir.setMinimumSize(new java.awt.Dimension(69, 23));
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setMaximumSize(new java.awt.Dimension(69, 23));
        jBtnGuardar.setMinimumSize(new java.awt.Dimension(69, 23));
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Alumno");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Documento :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Estado :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento :");

        jTextDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDniKeyTyped(evt);
            }
        });

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jBtnModificar.setText("Modificar");
        jBtnModificar.setEnabled(false);
        jBtnModificar.setMaximumSize(new java.awt.Dimension(69, 23));
        jBtnModificar.setMinimumSize(new java.awt.Dimension(69, 23));
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextDni, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBEstado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnBuscar)
                                    .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JDateFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(182, 182, 182))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnBuscar))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addComponent(jRBEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(JDateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnNuevo)
                    .addComponent(jBtnEliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //PRESIONO EL BOTON SALIR
    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed

        this.dispose(); //ME CIERRO

    }//GEN-LAST:event_jBtnSalirActionPerformed

    //PRESIONO EL BOTON NUEVO Y LIMPIO TODOS LOS DATOS
    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed

        //INICIO LOS BOTONES Y TEXTBOX
        IniciarControles();

    }//GEN-LAST:event_jBtnNuevoActionPerformed

    //PRESIONA EL BOTON BUSCAR
    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed

        AlumnoData alumnoData = new AlumnoData(); // INSTANCIO ALUMNO DATA PARA ACCEDER A LA BASE DE DATOS
        Alumno alumno = new Alumno();  //CREO UN ALUMNO

        if (jTextDni.getText().isEmpty()) { //VERIFICO QUE DNI SEA DISTINTO DE VACIO
            JOptionPane.showMessageDialog(this, "Error Ingresar DNI");
        } else {
            try {
                alumno = alumnoData.buscarAlumnoPorDni(Integer.parseInt(jTextDni.getText().trim())); //BUSCO EL DNI
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Erro al cargar DNI " + e.getMessage());
            }
            if (alumno != null) { //SI ALUMNO ES DISTINTO DE NULL LO ENCONTRO

                if (alumno.isActivo()) {

                    // MUESTRO LOS DATOS
                    jTextNombre.setText(alumno.getNombre());
                    jTextApellido.setText(alumno.getApellido());
                    jRBEstado.setSelected(alumno.isActivo());
                    JDateFechaNacimiento.setDate(Date.valueOf(alumno.getFechaNac()));
                    jTextDni.setEnabled(false);
                    //DESACTIVO EL BOTON ACTIVO LA UNICA FORMA DE BORRA ES POR EL BOTON
                    //jRBEstado.setEnabled(false);

                    //ACTIVO LOS BOTONES
                    jBtnEliminar.setEnabled(true);
                    jBtnModificar.setVisible(true);
                    jBtnModificar.setEnabled(true);
                    jBtnGuardar.setVisible(false);

                    alumnoEncontrado = true; // ACTIVO MI CLAVE PARA SABER QUE EL ALUMNO YA FUE ENCONTRADO
                    codigoAlumno = alumno.getIdAlumno();
                } else {

                    int respuesta = JOptionPane.showConfirmDialog(this, "Este alumno ya fue eliminado desea recuperarlo", "Confirmacion", JOptionPane.YES_NO_OPTION);
                    if (respuesta == 0) {
                        //ELIMINO EL ALUMNO
                        alumnoData.activoAlumno(alumno.getIdAlumno());
                        this.dispose();
                    } else {
                        //ACTIVO LOS BOTONES
                        IniciarControles();
                        this.dispose();
                    }
                }
            } else {

                JOptionPane.showMessageDialog(this, "Su DNI no corresponde a ningun alumno registrado");
                //ACTIVO LOS BOTONES
                IniciarControles();

            }
        }


    }//GEN-LAST:event_jBtnBuscarActionPerformed

    //SOLO DEJO INGRESAR NUMEROS
    private void jTextDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDniKeyTyped
        int key = evt.getKeyChar(); // guardo el codigo ASCII que genero el evento
        boolean numero = key >= 48 && key <= 57; //verifco si es un numero
        if (!numero) {
            evt.consume();  // NO LO ESCRIBE
        }
    }//GEN-LAST:event_jTextDniKeyTyped

    //PRESIONO EL BOTON GUARDAR
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed

        Alumno alumno = new Alumno();
        AlumnoData alumnoData = new AlumnoData();
        String fecha = ((JTextField) JDateFechaNacimiento.getDateEditor().getUiComponent()).getText();   //GUARDO LA FECHA EN FORMATO STRING

        //PRIMERO VERIFICO QUE TODO LOS DATOS SEAN INGRESADOS      
        if (jTextDni.getText().isEmpty() || jTextApellido.getText().isEmpty() || jTextNombre.getText().isEmpty()
                || !jRBEstado.isSelected() || fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todo los datos deben completarse");
        } else {
            //CARGO EL ALUMNO
            try {
                alumno.setDni(Integer.parseInt(jTextDni.getText()));
                alumno.setApellido(jTextApellido.getText());
                alumno.setNombre(jTextNombre.getText());
                alumno.setFechaNac(JDateFechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                alumno.setActivo(jRBEstado.isSelected());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error de tipo de datos " + e);
            }

            //SI INGRESO TODO LOS DATOS VERIFICO SI EL ALUMNO YA EXISTE
            if (!alumnoData.dniExiste(alumno.getDni())) {
                alumnoData.guardarAlumno(alumno);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "El Alumno ya se encuentra en la Base de Datos");
            }
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    //PRESIONO EL BOTON ELIMINAR ALUMNO
    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed

        AlumnoData alumnoData = new AlumnoData();
        Alumno alumno = new Alumno();
        //PRIMERO VERIFIQUE QUE TENGO UN DNI Y SEA CORRECTO
        if ((alumnoEncontrado) && (!jTextDni.getText().isEmpty())) {
            alumno = alumnoData.buscarAlumnoPorDni(Integer.parseInt(jTextDni.getText()));
            int respuesta = JOptionPane.showConfirmDialog(this, "Esta Seguro de eliminar el alumno", "Confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {
                //ELIMINO EL ALUMNO
                alumnoData.eliminarAlumno(alumno.getIdAlumno());
                this.dispose();
            } else {
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Imposible Borrar");
            this.dispose();
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    //MODIFICO EL ALUMNO
    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed

        Alumno alumno = new Alumno();
        AlumnoData alumnoData = new AlumnoData();
        String fecha = ((JTextField) JDateFechaNacimiento.getDateEditor().getUiComponent()).getText();   //GUARDO LA FECHA EN FORMATO STRING

        //PRIMERO VERIFICO QUE TODO LOS DATOS SEAN INGRESADOS      
        if (jTextDni.getText().isEmpty() || jTextApellido.getText().isEmpty() || jTextNombre.getText().isEmpty()
                || !jRBEstado.isSelected() || fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todo los datos deben completarse");
        } else {
            //CARGO EL ALUMNO
            try {
                alumno.setIdAlumno(codigoAlumno);
                alumno.setDni(Integer.parseInt(jTextDni.getText()));
                alumno.setApellido(jTextApellido.getText());
                alumno.setNombre(jTextNombre.getText());
                alumno.setFechaNac(JDateFechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                alumno.setActivo(jRBEstado.isSelected());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error de tipo de datos " + e);
            }

            int respuesta = JOptionPane.showConfirmDialog(this, "Esta Seguro que desea modificar el alumno", "Confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {
                //MODIFICO EL ALUMNO
                alumnoData.modificarAlumno(alumno);
                this.dispose();
            } else {
                this.dispose();
            }
        }

    }//GEN-LAST:event_jBtnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateFechaNacimiento;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
