/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage.vistas;

import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import newpackage.entidades.Alumno;
import newpackage.entidades.Inscripcion;
import newpackage.entidades.Materia;

/**
 *
 * @author Usuario
 */
public class Inscripciones extends javax.swing.JInternalFrame {

    private Alumno alumno = new Alumno();
    private AlumnoData alumnoData = new AlumnoData();
    private Alumno alumnoSeleccionado = new Alumno();
    private InscripcionData inscData = new InscripcionData();
    private Inscripcion inscripcion;
    private int idMateria;
    
    private DefaultTableModel modeloTabla = new DefaultTableModel(){ // Creo un modelo de tabla
        public boolean isCellEditable(int f, int c){
            return false; // Indica que todas las celdas de la tabla no son editables
        }
    };
    /**
     * Creates new form Inscripciones
     */
    public Inscripciones() {
        initComponents();
        cargarComboBoxAlumno();
        cabeceraDeTabla();
        jbInscribir.setEnabled(false); //Desactivar Boton Inscribir
        jbAnularInscripcion.setEnabled(false); //Desactivar Boton Anular
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRbMateriasNoInscriptas = new javax.swing.JRadioButton();
        jbInscribir = new javax.swing.JButton();
        jbAnularInscripcion = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCbAlumnos = new javax.swing.JComboBox<>();
        jRbMateriasInscriptas = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(null);
        setClosable(true);

        jRbMateriasNoInscriptas.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jRbMateriasNoInscriptas.setText("Materias no inscriptas");
        jRbMateriasNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbMateriasNoInscriptasActionPerformed(evt);
            }
        });

        jbInscribir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInscribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-más-50.png"))); // NOI18N
        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbAnularInscripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbAnularInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-basura-501.png"))); // NOI18N
        jbAnularInscripcion.setText("Anular Inscripción");
        jbAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscripcionActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-salir-50.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtMaterias);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Formulario de Inscripción");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Selección de alumno:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Listado de Materias");

        jCbAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbAlumnosMouseClicked(evt);
            }
        });
        jCbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbAlumnosActionPerformed(evt);
            }
        });

        jRbMateriasInscriptas.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jRbMateriasInscriptas.setText("Materias inscriptas");
        jRbMateriasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbMateriasInscriptasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRbMateriasInscriptas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRbMateriasNoInscriptas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbInscribir)
                        .addGap(94, 94, 94)
                        .addComponent(jbAnularInscripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbMateriasNoInscriptas)
                    .addComponent(jRbMateriasInscriptas))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbAnularInscripcion)
                    .addComponent(jbSalir))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRbMateriasNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbMateriasNoInscriptasActionPerformed
        // TODO add your handling code here:
        jbAnularInscripcion.setEnabled(false); //Desactivar Boton Anular
        jbInscribir.setEnabled(false); //Desactivar Boton Inscribir
        jRbMateriasInscriptas.setSelected(false); //Des-seleccionar RadioButton Materias Inscriptas
        //List<Materia> obtenerMateriasNoCursadas(alumnoSeleccionado.getIdAlumno())
        List<Materia> listaMaterias = new ArrayList<Materia>();
        listaMaterias = inscData.obtenerMateriasNoCursadas(alumnoSeleccionado.getIdAlumno());
        limpiarTabla();
        if (listaMaterias.isEmpty()) {
            jbInscribir.setEnabled(false); //Desactivar Boton Anular
            JOptionPane.showMessageDialog(null, "El alumno se inscribió en todas las materias", "MENSAJE", 1);
        } else {
            for (Materia materia : listaMaterias) {
                cargarDatosEnLaTabla(materia);
            }
        }
    }//GEN-LAST:event_jRbMateriasNoInscriptasActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        // TODO add your handling code here:
        inscripcion.setNota(-1); // Nota -1 para indicar que no tiene nota aun
        inscData.guardarInscripcion(inscripcion);
        jRbMateriasNoInscriptasActionPerformed(evt);
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscripcionActionPerformed
        // TODO add your handling code here:
        inscData.borrarInscripcionMateriaAlumno(alumnoSeleccionado.getIdAlumno(), idMateria);
        jRbMateriasInscriptasActionPerformed(evt);
    }//GEN-LAST:event_jbAnularInscripcionActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose(); //Salir
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jCbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbAlumnosActionPerformed
//        // TODO add your handling code here:
        alumnoSeleccionado = (Alumno) jCbAlumnos.getSelectedItem();
    }//GEN-LAST:event_jCbAlumnosActionPerformed

    private void jRbMateriasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbMateriasInscriptasActionPerformed
        // TODO add your handling code here:
        jbInscribir.setEnabled(false); //Desactivar Boton Inscribir
        jbAnularInscripcion.setEnabled(false); //Desactivar Boton Anular
        jRbMateriasNoInscriptas.setSelected(false); //Des-seleccionar RadioButton Materias No Inscriptas
        //Llenar la tabla List<Materia> obtenerMateriasCursadas(alumnoSeleccionado.getIdAlumno()) InscripcionData
        List<Materia> listaMaterias = new ArrayList<Materia>();
        listaMaterias = inscData.obtenerMateriasCursadas(alumnoSeleccionado.getIdAlumno());
        limpiarTabla();
        if (listaMaterias.isEmpty()) {
            jbAnularInscripcion.setEnabled(false); //Desactivar Boton Anular
            JOptionPane.showMessageDialog(null, "El alumno no tiene materias inscriptas", "MENSAJE", 1);
        } else {
            for (Materia materia : listaMaterias) {
                cargarDatosEnLaTabla(materia);
            }
        }
    }//GEN-LAST:event_jRbMateriasInscriptasActionPerformed

    private void jCbAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbAlumnosMouseClicked
        // TODO add your handling code here:
        jRbMateriasNoInscriptas.setSelected(false); //Des-seleccionar RadioButton Materias No Inscriptas
        jRbMateriasInscriptas.setSelected(false); //Des-seleccionar RadioButton Materias Inscriptas
        jbInscribir.setEnabled(false); //Desactivar Boton Inscribir
        jbAnularInscripcion.setEnabled(false); //Desactivar Boton Anular
        limpiarTabla();        
    }//GEN-LAST:event_jCbAlumnosMouseClicked

    private void jtMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMateriasMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = jtMaterias.getSelectedRow();
        if (filaSeleccionada!=-1){
            idMateria = (Integer)jtMaterias.getValueAt(filaSeleccionada, 0);
            MateriaData matData = new MateriaData();
            inscripcion = new Inscripcion(alumnoSeleccionado, matData.buscarMateria(idMateria));
            if(jRbMateriasNoInscriptas.isSelected()){
                jbInscribir.setEnabled(true); //Desactivar Boton Inscribir
                jbAnularInscripcion.setEnabled(false); //Activar Boton Anular
            }
            if(jRbMateriasInscriptas.isSelected()){
                jbInscribir.setEnabled(false); //Desactivar Boton Inscribir
                jbAnularInscripcion.setEnabled(true); //Activar Boton Anular
            }
        }
    }//GEN-LAST:event_jtMateriasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> jCbAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRbMateriasInscriptas;
    private javax.swing.JRadioButton jRbMateriasNoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAnularInscripcion;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTable jtMaterias;
    // End of variables declaration//GEN-END:variables

    private void cabeceraDeTabla(){
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Año");
        jtMaterias.setModel(modeloTabla);
    }
    
    private void cargarComboBoxAlumno(){
        ArrayList<Alumno> listaAlumnos = new ArrayList<Alumno>();
        listaAlumnos = alumnoData.listarAlumnos();
        for (Alumno alumno : listaAlumnos) {
            jCbAlumnos.addItem(alumno);
        }
    }
    
    private void cargarDatosEnLaTabla(Materia materia){
        modeloTabla.addRow(new Object[]{materia.getIdMateria(), materia.getNombre(), materia.getAnioMateria()});
    }
    
    public void limpiarTabla(){
        DefaultTableModel model = (DefaultTableModel) jtMaterias.getModel();
        int filas = jtMaterias.getRowCount()-1;
        for (int i = filas; i >= 0; i--) {          
            model.removeRow(model.getRowCount()-1);
        }
    }

    private void Dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
